//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCliente.ProgressoWSDL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://calculator.me.org/", ConfigurationName="ProgressoWSDL.ProgressWS")]
    public interface ProgressWS {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ra no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://calculator.me.org/ProgressWS/getProgressRequest", ReplyAction="http://calculator.me.org/ProgressWS/getProgressResponse")]
        WebServiceCliente.ProgressoWSDL.getProgressResponse getProgress(WebServiceCliente.ProgressoWSDL.getProgressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calculator.me.org/ProgressWS/getProgressRequest", ReplyAction="http://calculator.me.org/ProgressWS/getProgressResponse")]
        System.Threading.Tasks.Task<WebServiceCliente.ProgressoWSDL.getProgressResponse> getProgressAsync(WebServiceCliente.ProgressoWSDL.getProgressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProgressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProgress", Namespace="http://calculator.me.org/", Order=0)]
        public WebServiceCliente.ProgressoWSDL.getProgressRequestBody Body;
        
        public getProgressRequest() {
        }
        
        public getProgressRequest(WebServiceCliente.ProgressoWSDL.getProgressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getProgressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ra;
        
        public getProgressRequestBody() {
        }
        
        public getProgressRequestBody(string ra) {
            this.ra = ra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProgressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProgressResponse", Namespace="http://calculator.me.org/", Order=0)]
        public WebServiceCliente.ProgressoWSDL.getProgressResponseBody Body;
        
        public getProgressResponse() {
        }
        
        public getProgressResponse(WebServiceCliente.ProgressoWSDL.getProgressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getProgressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getProgressResponseBody() {
        }
        
        public getProgressResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProgressWSChannel : WebServiceCliente.ProgressoWSDL.ProgressWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProgressWSClient : System.ServiceModel.ClientBase<WebServiceCliente.ProgressoWSDL.ProgressWS>, WebServiceCliente.ProgressoWSDL.ProgressWS {
        
        public ProgressWSClient() {
        }
        
        public ProgressWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProgressWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgressWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgressWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceCliente.ProgressoWSDL.getProgressResponse WebServiceCliente.ProgressoWSDL.ProgressWS.getProgress(WebServiceCliente.ProgressoWSDL.getProgressRequest request) {
            return base.Channel.getProgress(request);
        }
        
        public string getProgress(string ra) {
            WebServiceCliente.ProgressoWSDL.getProgressRequest inValue = new WebServiceCliente.ProgressoWSDL.getProgressRequest();
            inValue.Body = new WebServiceCliente.ProgressoWSDL.getProgressRequestBody();
            inValue.Body.ra = ra;
            WebServiceCliente.ProgressoWSDL.getProgressResponse retVal = ((WebServiceCliente.ProgressoWSDL.ProgressWS)(this)).getProgress(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceCliente.ProgressoWSDL.getProgressResponse> WebServiceCliente.ProgressoWSDL.ProgressWS.getProgressAsync(WebServiceCliente.ProgressoWSDL.getProgressRequest request) {
            return base.Channel.getProgressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceCliente.ProgressoWSDL.getProgressResponse> getProgressAsync(string ra) {
            WebServiceCliente.ProgressoWSDL.getProgressRequest inValue = new WebServiceCliente.ProgressoWSDL.getProgressRequest();
            inValue.Body = new WebServiceCliente.ProgressoWSDL.getProgressRequestBody();
            inValue.Body.ra = ra;
            return ((WebServiceCliente.ProgressoWSDL.ProgressWS)(this)).getProgressAsync(inValue);
        }
    }
}
