//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCliente.PerguntasWSDL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="PerguntasWSDL.Perguntas")]
    public interface Perguntas {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/Perguntas/getQuestaoRequest", ReplyAction="http://services/Perguntas/getQuestaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServiceCliente.PerguntasWSDL.getQuestaoResponse getQuestao(WebServiceCliente.PerguntasWSDL.getQuestaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/Perguntas/getQuestaoRequest", ReplyAction="http://services/Perguntas/getQuestaoResponse")]
        System.Threading.Tasks.Task<WebServiceCliente.PerguntasWSDL.getQuestaoResponse> getQuestaoAsync(WebServiceCliente.PerguntasWSDL.getQuestaoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/Perguntas/setRespostaRequest", ReplyAction="http://services/Perguntas/setRespostaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServiceCliente.PerguntasWSDL.setRespostaResponse setResposta(WebServiceCliente.PerguntasWSDL.setRespostaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/Perguntas/setRespostaRequest", ReplyAction="http://services/Perguntas/setRespostaResponse")]
        System.Threading.Tasks.Task<WebServiceCliente.PerguntasWSDL.setRespostaResponse> setRespostaAsync(WebServiceCliente.PerguntasWSDL.setRespostaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class questoes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aField;
        
        private string bField;
        
        private string cField;
        
        private string corretaField;
        
        private string dField;
        
        private string eField;
        
        private string enunciadoField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string a {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
                this.RaisePropertyChanged("a");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string b {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
                this.RaisePropertyChanged("b");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string c {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
                this.RaisePropertyChanged("c");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correta {
            get {
                return this.corretaField;
            }
            set {
                this.corretaField = value;
                this.RaisePropertyChanged("correta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string d {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
                this.RaisePropertyChanged("d");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string e {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
                this.RaisePropertyChanged("e");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string enunciado {
            get {
                return this.enunciadoField;
            }
            set {
                this.enunciadoField = value;
                this.RaisePropertyChanged("enunciado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQuestao", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class getQuestaoRequest {
        
        public getQuestaoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQuestaoResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class getQuestaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebServiceCliente.PerguntasWSDL.questoes @return;
        
        public getQuestaoResponse() {
        }
        
        public getQuestaoResponse(WebServiceCliente.PerguntasWSDL.questoes @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setResposta", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class setRespostaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int questao;
        
        public setRespostaRequest() {
        }
        
        public setRespostaRequest(string ra, string resp, int questao) {
            this.ra = ra;
            this.resp = resp;
            this.questao = questao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setRespostaResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class setRespostaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public setRespostaResponse() {
        }
        
        public setRespostaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PerguntasChannel : WebServiceCliente.PerguntasWSDL.Perguntas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerguntasClient : System.ServiceModel.ClientBase<WebServiceCliente.PerguntasWSDL.Perguntas>, WebServiceCliente.PerguntasWSDL.Perguntas {
        
        public PerguntasClient() {
        }
        
        public PerguntasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerguntasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerguntasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerguntasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceCliente.PerguntasWSDL.getQuestaoResponse WebServiceCliente.PerguntasWSDL.Perguntas.getQuestao(WebServiceCliente.PerguntasWSDL.getQuestaoRequest request) {
            return base.Channel.getQuestao(request);
        }
        
        public WebServiceCliente.PerguntasWSDL.questoes getQuestao() {
            WebServiceCliente.PerguntasWSDL.getQuestaoRequest inValue = new WebServiceCliente.PerguntasWSDL.getQuestaoRequest();
            WebServiceCliente.PerguntasWSDL.getQuestaoResponse retVal = ((WebServiceCliente.PerguntasWSDL.Perguntas)(this)).getQuestao(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceCliente.PerguntasWSDL.getQuestaoResponse> WebServiceCliente.PerguntasWSDL.Perguntas.getQuestaoAsync(WebServiceCliente.PerguntasWSDL.getQuestaoRequest request) {
            return base.Channel.getQuestaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceCliente.PerguntasWSDL.getQuestaoResponse> getQuestaoAsync() {
            WebServiceCliente.PerguntasWSDL.getQuestaoRequest inValue = new WebServiceCliente.PerguntasWSDL.getQuestaoRequest();
            return ((WebServiceCliente.PerguntasWSDL.Perguntas)(this)).getQuestaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceCliente.PerguntasWSDL.setRespostaResponse WebServiceCliente.PerguntasWSDL.Perguntas.setResposta(WebServiceCliente.PerguntasWSDL.setRespostaRequest request) {
            return base.Channel.setResposta(request);
        }
        
        public bool setResposta(string ra, string resp, int questao) {
            WebServiceCliente.PerguntasWSDL.setRespostaRequest inValue = new WebServiceCliente.PerguntasWSDL.setRespostaRequest();
            inValue.ra = ra;
            inValue.resp = resp;
            inValue.questao = questao;
            WebServiceCliente.PerguntasWSDL.setRespostaResponse retVal = ((WebServiceCliente.PerguntasWSDL.Perguntas)(this)).setResposta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceCliente.PerguntasWSDL.setRespostaResponse> WebServiceCliente.PerguntasWSDL.Perguntas.setRespostaAsync(WebServiceCliente.PerguntasWSDL.setRespostaRequest request) {
            return base.Channel.setRespostaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceCliente.PerguntasWSDL.setRespostaResponse> setRespostaAsync(string ra, string resp, int questao) {
            WebServiceCliente.PerguntasWSDL.setRespostaRequest inValue = new WebServiceCliente.PerguntasWSDL.setRespostaRequest();
            inValue.ra = ra;
            inValue.resp = resp;
            inValue.questao = questao;
            return ((WebServiceCliente.PerguntasWSDL.Perguntas)(this)).setRespostaAsync(inValue);
        }
    }
}
